spring.application.name=FinalProject

#datasource (oracle)
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@43.201.115.54:1521/xe
spring.datasource.username=dev01
spring.datasource.password=dev01
#mybatis
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=VARCHAR
mybatis.type-aliases-package=com.example.demo
mybatis.mapper-locations=classpath:mapper/**/*.xml

# smtp server login
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=parksw9659@gmail.com
spring.mail.password=ifpfeamgmypjlwyl

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true